// The Qur'an corpus, as a Postgres schema — a faithful, column-for-column translation of
// quran.db (the SQLite file the pipeline builds). Step 1 of moving the corpus to the cloud:
// the DATA moves and is verified here; the query layer still reads SQLite until it is ported.
//
// Translation rules (SQLite → Postgres), chosen so the copy BEHAVES the same, not just looks it:
//   • every text column is `COLLATE "C"` — byte order, the exact equivalent of SQLite's default
//     BINARY collation. The database's own collation (English_United States.1252 here) would
//     otherwise re-sort and re-compare Arabic differently from what the app does today.
//   • INTEGER → integer (int4: every id and count here fits, and pg returns int4 as a JS number,
//     so values round-trip unchanged). INTEGER PRIMARY KEY AUTOINCREMENT → an identity column
//     (BY DEFAULT, so the original ids are copied verbatim; sequences are advanced after load).
//   • BLOB → bytea.
//   • The two FTS5 tables are EXTERNAL-CONTENT indexes over `verses` / `verse_translations`, so
//     they carry no data of their own: they become GIN full-text indexes on those tables.
//   • Foreign keys, secondary indexes, the view and the full-text indexes are created AFTER the
//     bulk load (faster, and order-independent). PK + UNIQUE stay on the tables so a duplicate
//     row fails the load instead of slipping in.

export const SCHEMA = "corpus";

/** A corpus table and its key — the key drives keyset pagination during verification. */
export interface TableSpec {
  name: string;
  pk: string;
  /** an identity column whose sequence must be advanced past the copied ids */
  identity?: boolean;
}

/** Load order follows the foreign-key graph (not required — FKs come after — but readable). */
export const TABLES: TableSpec[] = [
  { name: "_meta", pk: "key" },
  { name: "chapters", pk: "id" },
  { name: "juzs", pk: "id" },
  { name: "roots", pk: "id", identity: true },
  { name: "root_forms", pk: "id", identity: true },
  { name: "root_meanings", pk: "id", identity: true },
  { name: "translation_resources", pk: "id" },
  { name: "verses", pk: "id" },
  { name: "verse_embeddings", pk: "verse_id" },
  { name: "verse_translations", pk: "id", identity: true },
  { name: "words", pk: "id" },
  { name: "word_segments", pk: "id", identity: true },
];

const T = `text COLLATE "C"`;

/** Tables only: primary keys and uniqueness, no foreign keys or secondary indexes yet. */
export const CREATE_TABLES = `
CREATE TABLE ${SCHEMA}._meta (
  "key"   ${T} PRIMARY KEY,
  "value" ${T}
);

CREATE TABLE ${SCHEMA}.chapters (
  id               integer PRIMARY KEY,
  name_simple      ${T} NOT NULL,
  name_arabic      ${T},
  name_complex     ${T},
  revelation_place ${T},
  revelation_order integer,
  bismillah_pre    integer,
  verses_count     integer,
  pages_first      integer,
  pages_last       integer
);

CREATE TABLE ${SCHEMA}.juzs (
  id             integer PRIMARY KEY,
  juz_number     integer NOT NULL,
  verse_mapping  ${T},
  first_verse_id integer,
  last_verse_id  integer,
  verses_count   integer
);

CREATE TABLE ${SCHEMA}.roots (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  root_buckwalter ${T} NOT NULL UNIQUE,
  root_arabic     ${T} NOT NULL,
  letters_arabic  ${T},
  letter_count    integer,
  meaning_en      ${T},
  meaning_ar      ${T}
);

CREATE TABLE ${SCHEMA}.root_forms (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  root_id          integer NOT NULL,
  lemma_buckwalter ${T} NOT NULL,
  lemma_arabic     ${T},
  pos              ${T},
  pos_english      ${T},
  pos_arabic       ${T},
  pos_class        ${T},
  occurrence_count integer DEFAULT 0,
  UNIQUE (root_id, lemma_buckwalter, pos)
);

CREATE TABLE ${SCHEMA}.root_meanings (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  root_id    integer NOT NULL,
  source     ${T} NOT NULL,
  "language" ${T} NOT NULL,
  meaning    ${T} NOT NULL,
  source_ref ${T},
  UNIQUE (root_id, source, "language")
);

CREATE TABLE ${SCHEMA}.translation_resources (
  id            integer PRIMARY KEY,
  name          ${T},
  language_name ${T},
  author_name   ${T},
  resource_type ${T}
);

CREATE TABLE ${SCHEMA}.verses (
  id                   integer PRIMARY KEY,
  chapter_id           integer NOT NULL,
  verse_number         integer NOT NULL,
  verse_key            ${T} NOT NULL UNIQUE,
  verse_index          integer,
  text_uthmani         ${T},
  text_uthmani_simple  ${T},
  text_imlaei          ${T},
  text_imlaei_simple   ${T},
  text_indopak         ${T},
  text_uthmani_tajweed ${T},
  code_v1              ${T},
  code_v2              ${T},
  v1_page              integer,
  v2_page              integer,
  juz_number           integer,
  hizb_number          integer,
  rub_el_hizb_number   integer,
  page_number          integer,
  ruku_number          integer,
  manzil_number        integer,
  image_url            ${T}
);

CREATE TABLE ${SCHEMA}.verse_embeddings (
  verse_id  integer PRIMARY KEY,
  model     ${T},
  embedding bytea
);

CREATE TABLE ${SCHEMA}.verse_translations (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verse_id      integer NOT NULL,
  verse_key     ${T} NOT NULL,
  resource_id   integer NOT NULL,
  language_name ${T},
  "text"        ${T},
  UNIQUE (verse_id, resource_id)
);

CREATE TABLE ${SCHEMA}.words (
  id                       integer PRIMARY KEY,
  verse_id                 integer,
  verse_key                ${T} NOT NULL,
  "position"               integer NOT NULL,
  text_uthmani             ${T},
  text_imlaei              ${T},
  text_indopak             ${T},
  code_v1                  ${T},
  code_v2                  ${T},
  v1_page                  integer,
  v2_page                  integer,
  location                 ${T},
  page_number              integer,
  line_number              integer,
  char_type                ${T},
  audio_url                ${T},
  translation_text         ${T},
  translation_language     ${T},
  transliteration_text     ${T},
  transliteration_language ${T},
  root_form_id             integer,
  root_buckwalter          ${T},
  root_arabic              ${T},
  lemma_buckwalter         ${T},
  lemma_arabic             ${T},
  pos                      ${T},
  pos_arabic               ${T},
  pos_english              ${T},
  pos_class                ${T},
  UNIQUE (verse_key, "position")
);

CREATE TABLE ${SCHEMA}.word_segments (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verse_key        ${T} NOT NULL,
  word_position    integer NOT NULL,
  segment_number   integer NOT NULL,
  segment_type     ${T} NOT NULL,
  form_buckwalter  ${T},
  form_arabic      ${T},
  tag              ${T},
  pos              ${T},
  pos_arabic       ${T},
  pos_english      ${T},
  pos_class        ${T},
  prefix_type      ${T},
  prefix_arabic    ${T},
  prefix_english   ${T},
  lemma_buckwalter ${T},
  lemma_arabic     ${T},
  root_buckwalter  ${T},
  root_arabic      ${T},
  root_form_id     integer,
  verb_aspect      ${T},
  verb_voice       ${T},
  verb_mood        ${T},
  verb_form        ${T},
  derivation       ${T},
  noun_state       ${T},
  noun_case        ${T},
  person           ${T},
  gender           ${T},
  "number"         ${T},
  raw_features     ${T},
  UNIQUE (verse_key, word_position, segment_number)
);

-- The edition this copy holds, in the same keys the signed-patch channel uses
-- (corpus-core/src/corpus/patch.ts), plus where it came from.
CREATE TABLE ${SCHEMA}.corpus_meta (
  "key"   ${T} PRIMARY KEY,
  "value" ${T} NOT NULL
);
`;

/** Expected number of foreign keys after load — the verifier checks they all exist. */
export const FOREIGN_KEY_COUNT = 9;

/** Everything that is created after the rows are in. */
export const POST_LOAD = `
ALTER TABLE ${SCHEMA}.root_forms         ADD FOREIGN KEY (root_id)      REFERENCES ${SCHEMA}.roots(id);
ALTER TABLE ${SCHEMA}.root_meanings      ADD FOREIGN KEY (root_id)      REFERENCES ${SCHEMA}.roots(id) ON DELETE CASCADE;
ALTER TABLE ${SCHEMA}.verses             ADD FOREIGN KEY (chapter_id)   REFERENCES ${SCHEMA}.chapters(id);
ALTER TABLE ${SCHEMA}.verse_embeddings   ADD FOREIGN KEY (verse_id)     REFERENCES ${SCHEMA}.verses(id);
ALTER TABLE ${SCHEMA}.verse_translations ADD FOREIGN KEY (verse_id)     REFERENCES ${SCHEMA}.verses(id);
ALTER TABLE ${SCHEMA}.verse_translations ADD FOREIGN KEY (resource_id)  REFERENCES ${SCHEMA}.translation_resources(id);
ALTER TABLE ${SCHEMA}.words              ADD FOREIGN KEY (verse_id)     REFERENCES ${SCHEMA}.verses(id);
ALTER TABLE ${SCHEMA}.words              ADD FOREIGN KEY (root_form_id) REFERENCES ${SCHEMA}.root_forms(id);
ALTER TABLE ${SCHEMA}.word_segments      ADD FOREIGN KEY (root_form_id) REFERENCES ${SCHEMA}.root_forms(id);

CREATE INDEX idx_rf_lemma_ar     ON ${SCHEMA}.root_forms(lemma_arabic);
CREATE INDEX idx_rf_pos          ON ${SCHEMA}.root_forms(pos);
CREATE INDEX idx_rf_root_id      ON ${SCHEMA}.root_forms(root_id);
CREATE INDEX idx_rm_root_id      ON ${SCHEMA}.root_meanings(root_id);
CREATE INDEX idx_rm_source       ON ${SCHEMA}.root_meanings(source);
CREATE INDEX idx_roots_arabic    ON ${SCHEMA}.roots(root_arabic);
CREATE INDEX idx_seg_lemma_ar    ON ${SCHEMA}.word_segments(lemma_arabic);
CREATE INDEX idx_seg_pos         ON ${SCHEMA}.word_segments(pos);
CREATE INDEX idx_seg_root_ar     ON ${SCHEMA}.word_segments(root_arabic);
CREATE INDEX idx_seg_root_form   ON ${SCHEMA}.word_segments(root_form_id);
CREATE INDEX idx_seg_type        ON ${SCHEMA}.word_segments(segment_type);
CREATE INDEX idx_seg_verse_key   ON ${SCHEMA}.word_segments(verse_key);
CREATE INDEX idx_seg_word        ON ${SCHEMA}.word_segments(verse_key, word_position);
CREATE INDEX idx_verses_chapter  ON ${SCHEMA}.verses(chapter_id);
CREATE INDEX idx_verses_hizb     ON ${SCHEMA}.verses(hizb_number);
CREATE INDEX idx_verses_juz      ON ${SCHEMA}.verses(juz_number);
CREATE INDEX idx_verses_manzil   ON ${SCHEMA}.verses(manzil_number);
CREATE INDEX idx_verses_page     ON ${SCHEMA}.verses(page_number);
CREATE INDEX idx_verses_ruku     ON ${SCHEMA}.verses(ruku_number);
CREATE INDEX idx_vtrans_lang     ON ${SCHEMA}.verse_translations(language_name);
CREATE INDEX idx_vtrans_resource ON ${SCHEMA}.verse_translations(resource_id);
CREATE INDEX idx_vtrans_verse    ON ${SCHEMA}.verse_translations(verse_id);
CREATE INDEX idx_words_pos       ON ${SCHEMA}.words(pos);
CREATE INDEX idx_words_root_ar   ON ${SCHEMA}.words(root_arabic);
CREATE INDEX idx_words_root_form ON ${SCHEMA}.words(root_form_id);
CREATE INDEX idx_words_verse_id  ON ${SCHEMA}.words(verse_id);
CREATE INDEX idx_words_verse_key ON ${SCHEMA}.words(verse_key);

-- Replaces the FTS5 external-content tables verses_fts / translations_fts. 'simple' = lower-case
-- and split, no stemming — the nearest match to FTS5's unicode61. Exact search parity (how Arabic
-- diacritics tokenise) is settled in step 2, when the search queries themselves are ported.
CREATE INDEX verses_fts_gin ON ${SCHEMA}.verses USING gin (to_tsvector('simple',
  coalesce(verse_key, '') || ' ' || coalesce(text_uthmani, '') || ' ' ||
  coalesce(text_imlaei, '') || ' ' || coalesce(text_indopak, '')));
CREATE INDEX translations_fts_gin ON ${SCHEMA}.verse_translations
  USING gin (to_tsvector('simple', coalesce("text", '')));

-- Identical to quran.db's view: every STEM segment joined to its root, form, verse and word.
CREATE VIEW ${SCHEMA}.word_occurrences AS
SELECT
    ws.verse_key, ws.word_position, ws.form_arabic, ws.form_buckwalter,
    ws.pos, ws.pos_english, ws.pos_class,
    ws.verb_aspect, ws.verb_voice, ws.verb_mood, ws.verb_form, ws.derivation,
    ws.noun_case, ws.noun_state, ws.gender, ws."number", ws.person,
    r.id  AS root_id, r.root_arabic, r.root_buckwalter, r.letters_arabic, r.letter_count,
    rf.id AS root_form_id, rf.lemma_arabic, rf.lemma_buckwalter,
    v.chapter_id, v.verse_number, v.juz_number, v.page_number, v.ruku_number,
    w.audio_url, w.translation_text, w.code_v1, w.code_v2
FROM      ${SCHEMA}.word_segments ws
LEFT JOIN ${SCHEMA}.root_forms rf ON ws.root_form_id = rf.id
LEFT JOIN ${SCHEMA}.roots      r  ON rf.root_id      = r.id
LEFT JOIN ${SCHEMA}.verses     v  ON ws.verse_key    = v.verse_key
LEFT JOIN ${SCHEMA}.words      w  ON ws.verse_key    = w.verse_key
                                 AND ws.word_position = w."position"
WHERE ws.segment_type = 'STEM';
`;
