-- Every account's research, in ONE schema, `research`, kept apart by ROW-LEVEL SECURITY.
--
--   • every table carries user_id — defaulted from the request's user (app.user_id), leading
--     every key, and cascading from users: deleting an account deletes its research
--   • RLS is ENABLED and FORCED on every table, with one policy: a row is visible, and may be
--     written, only when its user_id is the request's user. No user set → nothing is visible and
--     nothing can be written (the NOT NULL default fails)
--   • requests run as mqrg_research, a role that is not a superuser and cannot bypass RLS (a
--     superuser bypasses every policy, FORCE or not — and the Docker image's database user is one)
--
-- The columns are exactly a research.db file's (server/src/research.ts SQLITE_SCHEMA) plus user_id;
-- remote/test/research-cloud.test.ts fails if they drift. Text is COLLATE "C" (byte order, as in
-- SQLite), timestamps are BIGINT milliseconds.

CREATE SCHEMA IF NOT EXISTS research;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mqrg_research') THEN
    CREATE ROLE mqrg_research NOLOGIN NOSUPERUSER NOBYPASSRLS NOINHERIT;
  END IF;
  -- the server's own login must be allowed to SET ROLE to it (a superuser already may; on a
  -- managed Postgres the owner usually isn't one)
  BEGIN
    EXECUTE format('GRANT mqrg_research TO %I', current_user);
  EXCEPTION WHEN others THEN NULL;
  END;
END $$;

-- the request's user, set per transaction by the research server (research/serve.ts)
CREATE OR REPLACE FUNCTION research.current_user_id() RETURNS uuid
  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;

CREATE TABLE IF NOT EXISTS research.cases (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, subject_type TEXT COLLATE "C" NOT NULL, subject_value TEXT COLLATE "C" NOT NULL,
  title TEXT COLLATE "C" NOT NULL DEFAULT '', status TEXT COLLATE "C" NOT NULL DEFAULT 'open',
  verdict TEXT COLLATE "C" NOT NULL DEFAULT '', spark_verse_key TEXT COLLATE "C",
  doc TEXT COLLATE "C" NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);
CREATE INDEX IF NOT EXISTS idx_cases_subject ON research.cases(user_id, subject_type, subject_value);
CREATE INDEX IF NOT EXISTS idx_cases_status ON research.cases(user_id, status);

CREATE TABLE IF NOT EXISTS research.form_research (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  case_id TEXT COLLATE "C" NOT NULL, root TEXT COLLATE "C" NOT NULL, lemma TEXT COLLATE "C" NOT NULL,
  status TEXT COLLATE "C" NOT NULL DEFAULT 'open', meaning TEXT COLLATE "C" NOT NULL DEFAULT '',
  established_at BIGINT, updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, case_id, lemma),
  FOREIGN KEY (user_id, case_id) REFERENCES research.cases(user_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_form_lemma ON research.form_research(user_id, lemma);
CREATE INDEX IF NOT EXISTS idx_form_root ON research.form_research(user_id, root);

CREATE TABLE IF NOT EXISTS research.form_revisions (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id TEXT COLLATE "C" NOT NULL, lemma TEXT COLLATE "C" NOT NULL,
  meaning TEXT COLLATE "C" NOT NULL, replaced_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rev_lemma ON research.form_revisions(user_id, case_id, lemma);

CREATE TABLE IF NOT EXISTS research.trails (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, name TEXT COLLATE "C" NOT NULL DEFAULT '', subject TEXT COLLATE "C",
  doc TEXT COLLATE "C" NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);

CREATE TABLE IF NOT EXISTS research.notes (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, verse_key TEXT COLLATE "C" NOT NULL, word_position BIGINT,
  kind TEXT COLLATE "C" NOT NULL DEFAULT 'note', text TEXT COLLATE "C" NOT NULL DEFAULT '',
  answer TEXT COLLATE "C" NOT NULL DEFAULT '', resolved BIGINT NOT NULL DEFAULT 0,
  lemma TEXT COLLATE "C", root TEXT COLLATE "C", source TEXT COLLATE "C" NOT NULL DEFAULT 'me',
  created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);
CREATE INDEX IF NOT EXISTS idx_notes_verse ON research.notes(user_id, verse_key);
CREATE INDEX IF NOT EXISTS idx_notes_lemma ON research.notes(user_id, lemma);
CREATE INDEX IF NOT EXISTS idx_notes_root ON research.notes(user_id, root);
CREATE INDEX IF NOT EXISTS idx_notes_source ON research.notes(user_id, source);

CREATE TABLE IF NOT EXISTS research.user_root_meanings (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  root TEXT COLLATE "C" NOT NULL, meaning TEXT COLLATE "C" NOT NULL DEFAULT '', updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, root)
);

CREATE TABLE IF NOT EXISTS research.motifs (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, name TEXT COLLATE "C" NOT NULL DEFAULT '', note TEXT COLLATE "C" NOT NULL DEFAULT '',
  source TEXT COLLATE "C" NOT NULL DEFAULT 'me', created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);
CREATE TABLE IF NOT EXISTS research.motif_roots (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  motif_id TEXT COLLATE "C" NOT NULL, root TEXT COLLATE "C" NOT NULL, added_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, motif_id, root)
);
CREATE INDEX IF NOT EXISTS idx_motif_roots_root ON research.motif_roots(user_id, root);

CREATE TABLE IF NOT EXISTS research.settings (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  key TEXT COLLATE "C" NOT NULL, value TEXT COLLATE "C" NOT NULL, updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS research.word_indications (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, lemma TEXT COLLATE "C", root TEXT COLLATE "C",
  scope TEXT COLLATE "C" NOT NULL DEFAULT 'lemma', parent_id TEXT COLLATE "C",
  label TEXT COLLATE "C" NOT NULL DEFAULT '', meaning TEXT COLLATE "C" NOT NULL DEFAULT '',
  is_primary BIGINT NOT NULL DEFAULT 0, source TEXT COLLATE "C" NOT NULL DEFAULT 'me',
  created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);
CREATE INDEX IF NOT EXISTS idx_word_indications_lemma ON research.word_indications(user_id, lemma);
CREATE INDEX IF NOT EXISTS idx_word_indications_root ON research.word_indications(user_id, root);
CREATE INDEX IF NOT EXISTS idx_word_indications_parent ON research.word_indications(user_id, parent_id);
CREATE INDEX IF NOT EXISTS idx_word_indications_source ON research.word_indications(user_id, source);

CREATE TABLE IF NOT EXISTS research.compare_sets (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, title TEXT COLLATE "C" NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  author_id TEXT COLLATE "C", origin TEXT COLLATE "C" NOT NULL DEFAULT 'local',
  PRIMARY KEY (user_id, id)
);
CREATE TABLE IF NOT EXISTS research.compare_items (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL, set_id TEXT COLLATE "C" NOT NULL,
  kind TEXT COLLATE "C" NOT NULL, ref TEXT COLLATE "C" NOT NULL, label TEXT COLLATE "C",
  created_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, id),
  UNIQUE (user_id, set_id, kind, ref)
);
CREATE INDEX IF NOT EXISTS idx_compare_items_set ON research.compare_items(user_id, set_id);

CREATE TABLE IF NOT EXISTS research.owner (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  id BIGINT NOT NULL CHECK (id = 1),
  name TEXT COLLATE "C" NOT NULL DEFAULT '', email TEXT COLLATE "C" NOT NULL, uuid TEXT COLLATE "C" NOT NULL,
  claimed_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, id)
);

CREATE TABLE IF NOT EXISTS research.derived_submissions (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  local_ref TEXT COLLATE "C" NOT NULL, submission_id TEXT COLLATE "C" NOT NULL,
  content_hash TEXT COLLATE "C" NOT NULL, kind TEXT COLLATE "C" NOT NULL DEFAULT '',
  status TEXT COLLATE "C" NOT NULL DEFAULT 'submitted', submitted_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, local_ref)
);
CREATE INDEX IF NOT EXISTS idx_derived_submissions_sub ON research.derived_submissions(user_id, submission_id);

CREATE TABLE IF NOT EXISTS research.derived_proposed_claims (
  user_id uuid NOT NULL DEFAULT research.current_user_id() REFERENCES public.users(id) ON DELETE CASCADE,
  subject_kind TEXT COLLATE "C" NOT NULL, subject_value TEXT COLLATE "C" NOT NULL,
  content_hash TEXT COLLATE "C" NOT NULL, proposed_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, subject_kind, subject_value)
);

-- the one rule, on every table: only the request's user's rows, for reading and for writing
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['cases','form_research','form_revisions','trails','notes','user_root_meanings',
    'motifs','motif_roots','settings','word_indications','compare_sets','compare_items','owner',
    'derived_submissions','derived_proposed_claims'] LOOP
    EXECUTE format('ALTER TABLE research.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE research.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS own_rows ON research.%I', t);
    EXECUTE format(
      'CREATE POLICY own_rows ON research.%I USING (user_id = research.current_user_id()) WITH CHECK (user_id = research.current_user_id())', t);
  END LOOP;
END $$;

GRANT USAGE ON SCHEMA research TO mqrg_research;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA research TO mqrg_research;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA research TO mqrg_research;
GRANT EXECUTE ON FUNCTION research.current_user_id() TO mqrg_research;

-- the per-account schemas this replaces (research_<id>, from the previous design) held no one's
-- real research yet; anything left of them is removed
DO $$
DECLARE s text;
BEGIN
  FOR s IN SELECT nspname FROM pg_namespace WHERE nspname ~ '^research_[0-9a-f]{32}$' LOOP
    EXECUTE format('DROP SCHEMA %I CASCADE', s);
  END LOOP;
END $$;
