// Buckwalter ⇄ Arabic transliteration table — ported verbatim from the server
// (server/src/text/constants.ts). Single source of truth for the text layer;
// do not edit without a matching round-trip test.

export const BUCKWALTER2UNICODE: Record<string, string> = {
  "'": "ء",
  "|": "آ",
  ">": "أ",
  "&": "ؤ",
  "<": "إ",
  "}": "ئ",
  A: "ا",
  b: "ب",
  p: "ة",
  t: "ت",
  v: "ث",
  j: "ج",
  H: "ح",
  x: "خ",
  d: "د",
  "*": "ذ",
  r: "ر",
  z: "ز",
  s: "س",
  $: "ش",
  S: "ص",
  D: "ض",
  T: "ط",
  Z: "ظ",
  E: "ع",
  g: "غ",
  _: "ـ",
  f: "ف",
  q: "ق",
  k: "ك",
  l: "ل",
  m: "م",
  n: "ن",
  h: "ه",
  w: "و",
  Y: "ى",
  y: "ي",
  F: "ً",
  N: "ٌ",
  K: "ٍ",
  a: "َ",
  u: "ُ",
  i: "ِ",
  "~": "ّ",
  o: "ْ",
  "`": "ٰ",
  "{": "ٱ",
  "^": "ٓ",
  "#": "ٔ",
  ":": "ۜ",
  "@": "۟",
  '"': "۠",
  "[": "ۢ",
  ";": "ۣ",
  ",": "ۥ",
  ".": "ۦ",
  "!": "ۨ",
  "-": "۪",
  "+": "۫",
  "%": "۬",
  "]": "ۭ",
};

export const UNICODE2BUCKWALTER: Record<string, string> = Object.fromEntries(
  Object.entries(BUCKWALTER2UNICODE).map(([bw, ar]) => [ar, bw]),
);
