// Parity: the TS text layer must reproduce the Python normalize.py output
// exactly (fixtures generated by gen_fixtures.py).

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  stripDiacritics, foldArabic, arabicToBuck, affixTrials, tokenizeArabic, normalizeRoot,
} from "../src/text/normalize.js";

const fx = JSON.parse(
  readFileSync(resolve(import.meta.dirname, "fixtures/normalize.json"), "utf-8"),
) as {
  cases: { input: string; strip: string; fold: string; buck: string; affix: string[]; tokenize: string[] }[];
  roots: { input: string; normalize_root: string }[];
};

describe("normalize parity with Python", () => {
  it("strip / fold / buck / affix / tokenize match for every sampled form", () => {
    for (const c of fx.cases) {
      expect(stripDiacritics(c.input), `strip ${c.input}`).toBe(c.strip);
      expect(foldArabic(c.input), `fold ${c.input}`).toBe(c.fold);
      expect(arabicToBuck(c.input), `buck ${c.input}`).toBe(c.buck);
      expect(affixTrials(foldArabic(c.input)), `affix ${c.input}`).toEqual(c.affix);
      expect(tokenizeArabic(c.input), `tokenize ${c.input}`).toEqual(c.tokenize);
    }
  });

  it("normalizeRoot matches for Buckwalter / joined / spaced input", () => {
    for (const r of fx.roots) {
      expect(normalizeRoot(r.input), `root ${r.input}`).toBe(r.normalize_root);
    }
  });
});
