// Every account's research lives in its OWN Postgres schema, research_<account id>. Privacy by
// construction: a request runs with search_path set to the signed-in user's schema only, so the
// shared research code — which never names a schema — can't see anyone else's rows. (And ids
// the app mints, like "c1", never collide across people.)
//
// The tables are derived from the research.db schema itself (server/src/research.ts
// SQLITE_SCHEMA), so a file and a schema always have the same shape:
//   INTEGER → BIGINT (millisecond timestamps), AUTOINCREMENT → identity,
//   TEXT → TEXT COLLATE "C" (byte order = SQLite's, so text sorts identically),
//   plus the author/origin stamp columns a file gains by migration.

import { ownerIdFor, normalizeEmail } from "../../../server/src/identity.js";
import { SQLITE_SCHEMA, LATER_INDEXES, STAMPED_TABLES } from "../../../server/src/research.js";

/** Bump when the research schema changes, and add the step to UPGRADES. */
export const RESEARCH_SCHEMA_VERSION = 1;
const UPGRADES: Record<number, string> = {
  // 2: "ALTER TABLE notes ADD COLUMN …",
};

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** The schema holding one account's research. Only ever built from an authenticated user id. */
export function schemaFor(userId: string): string {
  if (!UUID.test(userId)) throw new Error("not an account id");
  return `research_${userId.toLowerCase().replace(/-/g, "")}`;
}

/** The research tables in Postgres form, derived from the file's own DDL. */
export function pgResearchDDL(): string {
  const ddl = SQLITE_SCHEMA
    .replace(/--[^\n]*/g, "")
    .replace(/\bINTEGER PRIMARY KEY AUTOINCREMENT\b/g, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bINTEGER\b/g, "BIGINT")
    .replace(/\bTEXT\b/g, 'TEXT COLLATE "C"');
  const stamps = STAMPED_TABLES.map((t) =>
    `ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS author_id TEXT COLLATE "C";\n` +
    `ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS origin TEXT COLLATE "C" NOT NULL DEFAULT 'local';`).join("\n");
  return `${ddl}\n${stamps}\n${LATER_INDEXES.join(";\n")};\n` +
    `CREATE TABLE IF NOT EXISTS _research_meta (id INTEGER PRIMARY KEY CHECK (id = 1), version INTEGER NOT NULL);`;
}

/** One connection, inside the request's transaction. */
export interface ResearchConn {
  query(sql: string, params?: unknown[]): Promise<{ rows: Record<string, unknown>[]; rowCount: number }>;
}

const ready = new Set<string>();   // schemas known to be current, per process

/**
 * Make sure the account's schema exists and is current, creating it on first use (with the owner
 * record the research code reads). Runs inside the caller's transaction, under an advisory lock
 * so two first requests at once can't both try to create it.
 * Returns the schema name; the caller then sets search_path to it.
 */
export async function ensureResearchSchema(
  conn: ResearchConn, userId: string, profile: () => Promise<{ email: string; name: string }>,
): Promise<string> {
  const schema = schemaFor(userId);
  if (ready.has(schema)) return schema;
  await conn.query("SELECT pg_advisory_xact_lock(hashtext($1))", [schema]);
  const exists = (await conn.query("SELECT to_regclass($1) AS t", [`${schema}._research_meta`])).rows[0]?.t;
  if (!exists) {
    const who = await profile();
    await conn.query(`CREATE SCHEMA IF NOT EXISTS "${schema}"`);
    await conn.query(`SET LOCAL search_path TO "${schema}"`);
    for (const stmt of pgResearchDDL().split(";").map((s) => s.trim()).filter(Boolean)) await conn.query(stmt);
    const email = normalizeEmail(who.email), t = Date.now();
    // the same uuid a research.db of this person carries, so imported work stays theirs
    await conn.query(
      `INSERT INTO owner (id, name, email, uuid, claimed_at, updated_at) VALUES (1, $1, $2, $3, $4, $4)
       ON CONFLICT (id) DO NOTHING`, [who.name ?? "", email, ownerIdFor(email), t]);
    await conn.query("INSERT INTO _research_meta (id, version) VALUES (1, $1)", [RESEARCH_SCHEMA_VERSION]);
  } else {
    await conn.query(`SET LOCAL search_path TO "${schema}"`);
    const v = Number((await conn.query("SELECT version FROM _research_meta WHERE id = 1")).rows[0]?.version ?? 0);
    for (let next = v + 1; next <= RESEARCH_SCHEMA_VERSION; next++) {
      const step = UPGRADES[next];
      if (step) for (const stmt of step.split(";").map((s) => s.trim()).filter(Boolean)) await conn.query(stmt);
      await conn.query("UPDATE _research_meta SET version = $1 WHERE id = 1", [next]);
    }
  }
  return schema;
}

/** Called once the transaction that created/checked the schema has committed. */
export const markReady = (schema: string) => { ready.add(schema); };
/** Tests start each case from scratch. */
export const forgetReadySchemas = () => ready.clear();
